[package]
name = "openzeppelin-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-cron-scheduler = "0.13.0"
log = "0.4"
chrono = "0.4"
env_logger = "0.11.5"
async-trait = "0.1"
web3 = "0.19.0"
glob = "0.3"
reqwest = { version = "0.12", features = ["json"] }
hex = "0.4"
futures = "0.3"
ethabi = "18.0.0"
stellar-horizon = "0.7.1"
base64 = "0.22"
stellar-rpc-client = "22.0.0"
stellar-xdr = "22.1.0"
stellar-strkey = "0.0.11"

[dev-dependencies]
tempfile = "3.2"
mockall = "0.13.1"
