[package]
name = "openzeppelin-monitor"
version = "0.1.0"
edition = "2021"
rust-version = "1.84"         #MSRV

[profile.release]
opt-level = 0
overflow-checks = false
panic = 'unwind'

[profile.test]
debug = true
opt-level = 0
overflow-checks = true
panic = 'unwind'

[dependencies]
async-trait = "0.1"
base64 = "0.22"
chrono = "0.4"
clap = { version = "4.5", features = ["cargo"] }
cron = "0.15.0"
dotenvy = "0.15.7"
email_address = "0.2.9"
env_logger = "0.11.5"
ethabi = "18.0.0"
futures = "0.3"
glob = "0.3"
hex = "0.4"
hmac = "0.12.0"
lettre = "0.11.11"
log = "0.4"
regex = "1.11.0"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.0"
stellar-horizon = "0.7.1"
stellar-rpc-client = "22.0.0"
stellar-strkey = "0.0.11"
stellar-xdr = "22.1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-cron-scheduler = "0.13.0"
urlencoding = "2.1.3"
web3 = "0.19.0"

[dev-dependencies]
cargo-llvm-cov = "0.6"
mockall = "0.13.1"
mockito = "1.6.1"
proptest = "1.6.0"
rand = "0.9.0"
tempfile = "3.2"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "openzeppelin-monitor"
