[build]
base = "/"
command = """
  rustup default stable &&
  cargo install cargo-make --locked --force &&
  cargo make rust-docs
  """
publish = "docs/rust_docs/doc"

[[redirects]]
from = "/"
to = "/openzeppelin_monitor"
