---
site:
  title: OpenZeppelin Monitor
  start_page: openzeppelin_monitor:ROOT:index.adoc

content:
  sources:
    - url: ../
      branches: HEAD
      start_path: docs

asciidoc:
  attributes:
    idprefix: ''

ui:
  bundle:
    url: https://github.com/stephengold/antora-ui-bundle/releases/download/v-sgold250101a/ui-bundle.zip
    snapshot: true

urls:
  redirect_facility: netlify

output:
  dir: build/site

antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options:
        start_on_load: true
