name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - integrate-codecov

jobs:
  Tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
          rustflags: ""

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run Tests
        env:
          LLVM_PROFILE_FILE: llvm-cov-%p-%m.profraw
          RUSTFLAGS: -Cinstrument-coverage
        run: cargo test

      - name: Cargo llvm-cov
        run: cargo llvm-cov --locked --lcov --output-path lcov.info

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
